# Generated by juwelier
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Juwelier::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-
# stub: scout-rig 0.1.0 ruby lib

Gem::Specification.new do |s|
  s.name = "scout-rig".freeze
  s.version = "0.1.0".freeze

  s.required_rubygems_version = Gem::Requirement.new(">= 0".freeze) if s.respond_to? :required_rubygems_version=
  s.require_paths = ["lib".freeze]
  s.authors = ["Miguel Vazquez".freeze]
  s.date = "1980-01-02"
  s.description = "Use other coding languages in your scout applications".freeze
  s.email = "mikisvaz@gmail.com".freeze
  s.extra_rdoc_files = [
    "LICENSE.txt",
    "README.rdoc"
  ]
  s.files = [
    ".document",
    ".vimproject",
    "LICENSE.txt",
    "README.rdoc",
    "Rakefile",
    "VERSION",
    "lib/scout-rig.rb",
    "lib/scout/python.rb",
    "lib/scout/python/paths.rb",
    "lib/scout/python/run.rb",
    "lib/scout/python/script.rb",
    "lib/scout/python/util.rb",
    "python/scout/__init__.py",
    "python/scout/__pycache__/__init__.cpython-310.pyc",
    "python/scout/__pycache__/workflow.cpython-310.pyc",
    "python/scout/workflow.py",
    "python/scout/workflow/remote.py",
    "python/test.py",
    "scout-rig.gemspec",
    "test/scout/python/test_script.rb",
    "test/scout/python/test_util.rb",
    "test/scout/test_python.rb",
    "test/test_helper.rb"
  ]
  s.homepage = "http://github.com/mikisvaz/scout-rig".freeze
  s.licenses = ["MIT".freeze]
  s.rubygems_version = "3.6.8".freeze
  s.summary = "Scouts rigging things together".freeze

  s.specification_version = 4

  s.add_development_dependency(%q<juwelier>.freeze, ["~> 2.1.0".freeze])
  s.add_runtime_dependency(%q<pycall>.freeze, ["> 0".freeze])
end

