# Generated by juwelier
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Juwelier::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-
# stub: scout-rig 0.2.0 ruby lib

Gem::Specification.new do |s|
  s.name = "scout-rig".freeze
  s.version = "0.2.0".freeze

  s.required_rubygems_version = Gem::Requirement.new(">= 0".freeze) if s.respond_to? :required_rubygems_version=
  s.require_paths = ["lib".freeze]
  s.authors = ["Miguel Vazquez".freeze]
  s.date = "1980-01-02"
  s.description = "Use other coding languages in your scout applications".freeze
  s.email = "mikisvaz@gmail.com".freeze
  s.extra_rdoc_files = [
    "LICENSE.txt",
    "README.md"
  ]
  s.files = [
    ".document",
    ".vimproject",
    "LICENSE.txt",
    "README.md",
    "Rakefile",
    "VERSION",
    "doc/Python.md",
    "lib/scout-rig.rb",
    "lib/scout/python.rb",
    "lib/scout/python/paths.rb",
    "lib/scout/python/run.rb",
    "lib/scout/python/script.rb",
    "lib/scout/python/util.rb",
    "lib/scout/workflow/python.rb",
    "lib/scout/workflow/python/inputs.rb",
    "lib/scout/workflow/python/task.rb",
    "python/scout/__init__.py",
    "python/scout/runner.py",
    "python/scout/workflow.py",
    "python/scout/workflow/remote.py",
    "python/test.py",
    "scout-rig.gemspec",
    "test/scout/python/test_run.rb",
    "test/scout/python/test_script.rb",
    "test/scout/python/test_util.rb",
    "test/scout/test_python.rb",
    "test/scout/workflow/python/test_task.rb",
    "test/scout/workflow/test_python.rb",
    "test/test_helper.rb"
  ]
  s.homepage = "http://github.com/mikisvaz/scout-rig".freeze
  s.licenses = ["MIT".freeze]
  s.rubygems_version = "3.7.0.dev".freeze
  s.summary = "Scouts rigging things together".freeze

  s.specification_version = 4

  s.add_development_dependency(%q<juwelier>.freeze, ["~> 2.1.0".freeze])
  s.add_runtime_dependency(%q<pycall>.freeze, ["> 0".freeze])
end

